version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: delta_admin
      MONGO_INITDB_ROOT_PASSWORD: delta_password

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: delta_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: delta_password
      ME_CONFIG_MONGODB_URL: mongodb://delta_admin:delta_password@mongo:27017/?authSource=admin
